class Command:
    ADVANCE = 1
    REVERSE = 2
    ADVANCE_LEFT = 3
    ADVANCE_RIGHT = 4
    REVERSE_LEFT = 5
    REVERSE_RIGHT = 6
    OBSTACLE_FRONT = 7
    OBSTACLE_BOTTOM = 8
    NONE_OBSTACLE_FRONT = 9
    NONE_OBSTACLE_BOTTOM = 10
    BRAKE = 11